// Objective-C API for talking to neoutils Go package.
//   gobind -lang=objc neoutils
//
// File is generated by gobind. Do not edit.

#ifndef __Neoutils_H__
#define __Neoutils_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class NeoutilsSharedSecret;
@class NeoutilsWallet;

/**
 * Shared Secret with 2 parts.
 */
@interface NeoutilsSharedSecret : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSData* _Nullable first;
@property (nonatomic) NSData* _Nullable second;
@end

@interface NeoutilsWallet : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * Create a new wallet.
 */
- (nullable instancetype)init;
@property (nonatomic) NSData* _Nullable publicKey;
@property (nonatomic) NSData* _Nullable privateKey;
@property (nonatomic) NSString* _Nonnull address;
@property (nonatomic) NSString* _Nonnull wif;
@property (nonatomic) NSData* _Nullable hashedSignature;
/**
 * Compute shared secret using ECDH
 */
- (NSData* _Nullable)computeSharedSecret:(NSData* _Nullable)publicKey;
@end

/**
 * Generate a wallet from a private key
 */
FOUNDATION_EXPORT NeoutilsWallet* _Nullable NeoutilsGenerateFromPrivateKey(NSString* _Nullable privateKey, NSError* _Nullable* _Nullable error);

/**
 * Generate a wallet from a WIF
 */
FOUNDATION_EXPORT NeoutilsWallet* _Nullable NeoutilsGenerateFromWIF(NSString* _Nullable wif, NSError* _Nullable* _Nullable error);

/**
 * Generate Shamir shared secret to SharedSecret struct.
 */
FOUNDATION_EXPORT NeoutilsSharedSecret* _Nullable NeoutilsGenerateShamirSharedSecret(NSString* _Nullable secret, NSError* _Nullable* _Nullable error);

/**
 * Create a new wallet.
 */
FOUNDATION_EXPORT NeoutilsWallet* _Nullable NeoutilsNewWallet(NSError* _Nullable* _Nullable error);

/**
 * Recover the secret from shared secrets.
 */
FOUNDATION_EXPORT NSString* _Nonnull NeoutilsRecoverFromSharedSecret(NSData* _Nullable first, NSData* _Nullable second, NSError* _Nullable* _Nullable error);

/**
 * Sign data using ECDSA with a private key
 */
FOUNDATION_EXPORT NSData* _Nullable NeoutilsSign(NSData* _Nullable data, NSString* _Nullable key, NSError* _Nullable* _Nullable error);

/**
 * Verify signed hash using public key
 */
FOUNDATION_EXPORT BOOL NeoutilsVerify(NSData* _Nullable publicKey, NSData* _Nullable signature, NSData* _Nullable hash);

#endif
