version: 2.1
jobs:
  test:
    working_directory: ~/neon-wallet-mobile
    docker:
      - image: circleci/node:16.20.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/neon-wallet-mobile
      - run:
          name: type check
          command: yarn ts-build
      - run:
          name: lint
          command: yarn lint
      - run:
          name: test
          command: yarn test

  node:
    working_directory: ~/neon-wallet-mobile
    docker:
      - image: cimg/node:16.20.0

    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: ~/neon-wallet-mobile
          paths:
            - node_modules

workflows:
  version: 2
  build:
    jobs:
      - node