/**
 * Wrapper Configuration
 */
import {DarkTheme} from '~src/themes/DarkTheme'
import {LightTheme} from '~src/themes/LightTheme'

export class WrapperConfig {
  readonly themes = [DarkTheme, LightTheme] as const

  readonly dataKeys = [
    '@onboarding_seen',
    '@welcome_to_nw_seen',
    '@welcome_hidden',
    '@changelog_hidden',
    '@number_of_versions',
    '@has_authentication',
    '@has_authentication_hard',
    '@settings',
    '@wallets',
    '@accounts',
    '@contacts',
    '@exchange',
    '@token_assets',
    '@neo_nodes',
    '@nodes',
    '@MultichainExchange',
  ] as const

  readonly routes = [
    'Modal',
    'Tab',
    'Onboarding',
    'WelcomeModal',
    'QuickTools',
    'ListWallets',
    'ListWalletsPage',
    'Contacts',
    'Settings',
    'SettingsPage',
    'More',
    'GetWallet',
    'GetAccount',
    'MyWallets',
    'MyWalletOptions',
    'WalletDetails',
    'MorePage',
    'Step1CreateWallet',
    'Step2CreateWallet',
    'Step3CreateWallet',
    'Step4CreateWallet',
    'Step5CreateWallet',
    'Step1BackupWallet',
    'Step2BackupWallet',
    'Step3BackupWallet',
    'CustomColor',
    'CreateAccountModal',
    'EditAccountModal',
    'QRCodeScan',
    'ReceiveModalStack',
    'ReceiveWalletSelectionModal',
    'ReceiveAccountSelectionModal',
    'ReceiveToAccountModal',
    'ReceiveQrCodeModal',
    'SendModalStack',
    'SendWalletSelectionModal',
    'SendAccountSelectionModal',
    'SendTransactionInputModal',
    'SendTransactionReviewModal',
    'SendTransactionConfirmationModal',
    'TipConfirmationModal',
    'Login',
    'LoginPage',
    'WalletContextModal',
    'AccountAssetDetail',
    'ReorderWalletModal',
    'PasscodeStack',
    'Passcode',
    'ConfirmPasscode',
    'VerifyPasscode',
    'ImportKey',
    'Passphrase',
    'ImportReadAccount',
    'CustomizeAccount',
    'ListTokenModal',
    'LanguagePickerModal',
    'CurrencyPickerModal',
    'ThemePickerModal',
    'NetworkPickerModal',
    'PersistContact',
    'ContactDetails',
    'AccountQRCode',
    'ContactsModal',
    'CopyContextModal',
    'TransactionDetails',
    'EditWalletModal',
    'SecurityModal',
    'ChangelogModal',
    'BlockchainListModal',
    'BlockchainListPage',
    'MnemonicSelectionList',
    'WalletConnectPage',
    'WCConnectionRequestModal',
    'WCConnectDappModal',
    'WCWalletSelectionModal',
    'WCAccountSelectionModal',
    'TransactionRequestModal',
    'AccountAssetScreen',
    'AccountConnectionsScreen',
    'AccountTransactionsScreen',
    'RawJsonModal',
  ] as const
}

export const wrapperConfig = new WrapperConfig()
