/**
 * Wrapper Configuration
 */
import { DarkTheme } from '~src/themes/DarkTheme'

export class WrapperConfig {
  readonly themes = [DarkTheme] as const

  readonly dataKeys = [
    '@onboarding_seen',
    '@welcome_to_nw_seen',
    '@welcome_hidden',
    '@changelog_hidden',
    '@number_of_versions',
    '@has_authentication',
    '@has_authentication_hard',
    '@settings',
    '@wallets',
    '@accounts',
    '@contacts',
    '@exchange',
    '@token_assets',
    '@neo_nodes',
    '@nodes',
    '@wcApprovalDate',
  ] as const

  readonly routes = [
    'Modal',
    'Tab',
    'Onboarding',
    'WelcomeModal',
    'AddressScanQuickToolsModal',
    'ListWallets',
    'ListWalletsPage',
    'Contacts',
    'Settings',
    'SettingsPage',
    'More',
    'GetWallet',
    'GetAccount',
    'MorePage',
    'Step1CreateWallet',
    'Step2CreateWallet',
    'Step3CreateWallet',
    'Step4CreateWallet',
    'Step5CreateWallet',
    'Step1BackupWallet',
    'Step2BackupWallet',
    'Step3BackupWallet',
    'CustomColor',
    'CreateAccountModal',
    'EditAccountModal',
    'QRCodeScan',
    'WalletSelectionModal',
    'AccountSelectionModal',
    'ReceiveTransactionModal',
    'ReceiveTransactionQrCodeModal',
    'SendTransactionModal',
    'SendTransactionReviewModal',
    'SendTransactionConfirmationModal',
    'TipConfirmationModal',
    'Login',
    'LoginPage',
    'WalletContextModal',
    'ReorderWalletModal',
    'PasscodeStack',
    'Passcode',
    'ConfirmPasscode',
    'VerifyPasscode',
    'ImportKey',
    'Passphrase',
    'ImportReadAccount',
    'ListTokenModal',
    'LanguagePickerModal',
    'CurrencyPickerModal',
    'ThemePickerModal',
    'NetworkPickerModal',
    'PersistContactModal',
    'ContactDetails',
    'AccountQRCode',
    'ContactsModal',
    'CopyContextModal',
    'EditWalletModal',
    'SecurityPickerModal',
    'ChangelogModal',
    'BlockchainListModal',
    'BlockchainListPage',
    'MnemonicSelectionList',
    'WalletConnect',
    'WalletConnectPage',
    'WCConnectionRequestModal',
    'WCConnectDappModal',
    'WCTransactionRequestModal',
    'AccountAssetScreen',
    'WCConnectionDetailsModal',
    'AccountConnectionsScreen',
    'AccountTransactionsScreen',
    'AccountNFTSScreen',
    'RawJsonModal',
    'SignatureScopeModal',
    'WCInvocationDetailsModal',
    'WebViewModal',
    'WalletSettingsView',
    'AccountSettingsView',
    'ExportKeyModal',
    'SetupCompletePage',
    'BackupInfoModal',
    'SecurityBackupCheckPage',
    'SecurityPage',
    'ProtocolsPage',
    'ProtocolEditPage',
    'EditNetworkModal',
    'QuickToolsModal',
    'AddContactAddressModal',
    'SelectChainModal',
  ] as const
}

export const wrapperConfig = new WrapperConfig()
