# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Get certificates"
  lane :certificates do
    sync_code_signing(
      type: "appstore",
      app_identifier: ['io.cityofzion.neon'],
      force_for_new_devices: true,
      readonly: true
    )

    # You can repeate the sync_code_signing with other types of certificates such as appstore and adhoc
    sync_code_signing(
      type: "appstore",
      app_identifier: 'io.cityofzion.neon',
      readonly: true
    )
  end

  desc "Generate new certificates"
  lane :generate_new_certificates do
    sync_code_signing(
      type: "appstore",
      app_identifier: ['io.cityofzion.neon'],
      force_for_new_devices: true,
      readonly: false
    )
    
    # You can repeate the sync_code_signing with other types of certificates such as appstore and adhoc

  end
  
  desc "Push a new beta build to TestFlight"
    lane :beta do
      keyFilePath = File.join(Dir.pwd, "AuthKey.p8")
      keyId = ENV['APP_STORE_CONNECT_API_KEY_KEY_ID']
      issuerId = ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID']

      api_key = app_store_connect_api_key(
        key_id: keyId,
        issuer_id: issuerId,
        key_filepath: keyFilePath,
      )

      testflight_current_build = latest_testflight_build_number(
        api_key: api_key
      )

      store_current_build = app_store_build_number(
        api_key: api_key
      )

      current_build_version = [testflight_current_build, store_current_build].max()

      new_build_version = current_build_version + 1

      increment_version_number(
        version_number: '1.0.46'
      )

      increment_build_number(
        xcodeproj: "Neon.xcodeproj",
        build_number: new_build_version,
        skip_info_plist: true
      )
      
      match(
        type: "appstore",
        clone_branch_directly: true,
        verbose: true
      )
  
      build_app(
        workspace: "Neon.xcworkspace",
        scheme: "Neon-release",
        export_method: "app-store"
      )
  
      app_store_connect_api_key(
        key_id: keyId,
        issuer_id: issuerId,
        key_filepath: keyFilePath
      )
  
      upload_to_testflight(
        skip_waiting_for_build_processing: true,
        distribute_external: true,
        notify_external_testers: true,
        team_id: 'bb874eec-4755-42a7-a707-c0ddd1b61389',
        team_name: 'Beta',
        api_key: api_key,
        changelog: 'deploy with fastlane'
      )
    end

  desc "Push a new staging build to TestFlight"
  lane :staging do
    keyFilePath = File.join(Dir.pwd, "AuthKey.p8")
    keyId = ENV['APP_STORE_CONNECT_API_KEY_KEY_ID']
    issuerId = ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID']
    
    api_key = app_store_connect_api_key(
      key_id: keyId,
      issuer_id: issuerId,
      key_filepath: keyFilePath,
    )
    testflight_current_build = latest_testflight_build_number(
      api_key: api_key
    )
    store_current_build = app_store_build_number(
      api_key: api_key
    )
    current_build_version = [testflight_current_build, store_current_build].max()
    new_build_version = current_build_version + 1
    increment_version_number(
      version_number: '1.0.46'
    )
    increment_build_number(
      xcodeproj: "Neon.xcodeproj",
      build_number: new_build_version,
      skip_info_plist: true
    )
    
    match(
      type: "appstore",
      clone_branch_directly: true,
      verbose: true
    )

    build_app(
      workspace: "Neon.xcworkspace",
      scheme: "Neon-release",
      export_method: "app-store"
    )

    app_store_connect_api_key(
      key_id: keyId,
      issuer_id: issuerId,
      key_filepath: keyFilePath
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      distribute_external: true,
      notify_external_testers: true,
      team_id: '89de6f4f-6d90-4e68-8394-69ddb6276eb3',
      team_name: 'Staging',
      api_key: api_key,
      changelog: 'deploy with fastlane'
    )
  end

  lane :check_build_version do
    keyFilePath = File.join(Dir.pwd, "AuthKey.p8")
    keyId = ENV['APP_STORE_CONNECT_API_KEY_KEY_ID']
    issuerId = ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID']

    api_key = app_store_connect_api_key(
      key_id: keyId,
      issuer_id: issuerId,
      key_filepath: keyFilePath,
    )

    current_build_number = latest_testflight_build_number(
      api_key: api_key
    )
   
   current_app_build = app_store_build_number(
      api_key: api_key
    )
   
    puts [current_app_build, current_build_number]
    puts [current_app_build, current_build_number].max()
    puts [current_app_build, current_build_number].max().is_a? Integer
    puts [current_app_build, current_build_number].max().is_a? String
  end
end
