# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Neon.xcodeproj")
    get_certificates( # Create or get certificate, and install it
    output_path: "./builds", # Download certificate in the build folder (you don't need to create the folder)
    filename: "development.cer"
  )
  get_provisioning_profile( # Create or get provisioning profile
    output_path: "./builds",  # Download provisioning profile in the build folder
    filename: "match_AppStore_iocityofzionneon_1617203405.mobileprovision" # Rename the local provisioning profile
  )
  update_project_provisioning( # Set the project provisioning profile (related in Xcode to the General > Signing Release section)
    xcodeproj: "Neon.xcodeproj",
    target_filter: "Neon", # Name of your project
    profile: "./builds/match_AppStore_iocityofzionneon_1617203405.mobileprovision",
    build_configuration: "Release"
  )
  update_project_team( # Set the right team on your project
    teamid: CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
  )
    build_app(
      workspace: "Neon.xcworkspace",
      scheme: "Neon-release",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: { 
          "io.cityofzion.neon" => "match AppStore io.cityofzion.neon 1617203405",
        }
      },
    )
  end
end
