# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    releaseFilePath = File.join(Dir.pwd, "..", "./neon.jks")
    store_password = prompt(text: "Signing Store Password: ")
    key_password = prompt(text: "Signing Key Password: ")
    key_alias = prompt(text: "Signing Key Alias: ")
    gradle(task: 'clean')
    android_set_version_code(
      gradle_file: "app/build.gradle" # optional
    )
    gradle(
      task: 'assemble',
      build_type: 'Release',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => releaseFilePath,
        "android.injected.signing.store.password" => store_password,
        "android.injected.signing.key.alias" => key_alias,
        "android.injected.signing.key.password" => key_password,
      }
    )
    upload_to_play_store(
      track: 'Open Alpha'
    )
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end
end
