name: Build

on:
  pull_request:
    branches:
      - master
      - staging
  push:
    branches:
      - '*'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8  
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install yarn
      run: npm install --global yarn

    - name: Install dependencies
      run: yarn --force

    - name: Create keystore file
      run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > android/app/keystore.jks
    - name: Build release APK
      env:
          KEYSTORE_PATH: keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          NODE_OPTIONS: "--max_old_space_size=4096"
      run: npm run android-release

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: android/app/build/outputs/apk/release/app-release.apk
