name: Detox Test
on:
  push:
    tags:
      - 'refs/tags/detox'
jobs:
  build-and-test:
    runs-on: macos-12

    steps:
    - name: Install Dependencies
      run: |
        brew install node
        npm install -g detox-cli

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.20.0

    - name: Install applesimutils
      run: |
        brew tap wix/brew
        brew install applesimutils

    - name: Check applesimutils
      run: applesimutils --list --byType "iPhone 14"

    - name: Install Yarn
      run: npm install -g yarn

    - name: Checkout and Install Project Dependencies
      uses: actions/checkout@v2

    - name: Install and Build Project
      run: |
        yarn
        yarn build:ios
        cd ios
        pod install
        cd ..
        detox build -c ios.sim.release

    - name: Run Detox Tests
      run: |
        detox test -c ios.sim.release