# .github/workflows/e2e-android.yml
name: Detox Test Android
on:
  push:
    tags:
      - 'detox_android'
      - 'e2e_android'
jobs:
  e2e-android:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Use specific Java version for sdkmanager to work
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          architecture: 'x64'   
          distribution: 'temurin' 

      - name: Install yarn
        run: npm install --global yarn    

      - name: Install Yarn dependencies
        run: yarn --force

      - name: Fix Android 31 links
        run: ln -s ${ANDROID_HOME}/build-tools/31.0.0/d8 ${ANDROID_HOME}/build-tools/31.0.0/dx && ln -s ${ANDROID_HOME}/build-tools/31.0.0/lib/d8.jar ${ANDROID_HOME}/build-tools/31.0.0/lib/dx.jar

      - name: Create keystore file
        run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > android/app/keystore.jks

      - name: Detox build
        env:
          KEYSTORE_PATH: keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        run: yarn detox build --configuration android.emu.release

      - name: Create and start Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: google_apis
          arch: x86_64
          profile: Pixel_6_API_31
          hardware-profiles: pixel_6

      - name: Detox test
        run: yarn detox test --configuration android.emu.release
        